services:
  phpmyadmin:
    build:
      context: ./phpmyadmin/docker
      dockerfile: Dockerfile
    image: custom-phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1 # Allow connection to arbitrary servers
      UPLOAD_LIMIT: 256M
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
    volumes:
      - './phpmyadmin/config/phpmyadmin.config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro'
      - './phpmyadmin/config:/local-config:ro'
      - 'phpmyadmin_sessions:/tmp/phpmyadmin_sessions'
    ports:
      - '${PMA_PORT:-8080}:80'
    restart: always
    networks:
      - shared

  redis:
    image: 'redis:8-alpine'
    container_name: shared-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
      - './config/${APP_ENV:-local}/redis.conf:/usr/local/etc/redis/redis.conf:ro'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  phpmyadmin_sessions:
    driver: local
  redis:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/redis
      o: bind
